# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.10-slim

WORKDIR /app

# Copy requirements and project files
COPY pyproject.toml ./
COPY README.md ./
COPY src ./src
COPY uv.lock ./

# Install build dependencies
RUN pip install --no-cache-dir hatchling

# Build and install the package
RUN pip install --no-cache-dir .

# Expose port if needed (optional)

# Use the entrypoint defined in pyproject.toml
CMD ["mcp-server-perplexity"]
